loginText=role=link[name="Log In"]
usernameField=role=textbox[name="Email or username"]
passwordField=role=textbox[name="Password"]
buttonContinue=role=button[name="Continue" exact=true]
buttonSignIn=role=button[name="Sign In"]
errorEmailRequired=id=error-cs-username-required
errorMessageWrongPassword=id=error-element-password
errorMessageEmptyPassword=id=error-cs-password-required
settingMenuDashboard=id=settings-menu-button
