
startForFreeLink=role=link[name="Start for Free" nth=1]
emailField=role=textbox[name="Email Address"]
cbTermsOfService=id=terms-of-service
buttonSignup=role=button[name="Sign up"]
errorSignUpEmailRequired=id=error-cs-email-required
errorInvalidFormatEmail=id=error-cs-email-invalid
errorMessageCbRequired=css=div.ulp-error-info.ulp-validator-error
errorMessagePasswordValidation=id=error-cs-password-password-too-weak
errorMessageAccountExist=id=error-element-email
confirmEmailText=text=Confirm your email address
passwordSecurityText=id=password-security-popover

